trigger:
- '*'

variables:
  buildConfiguration: 'Release'

stages:
- template: stages/build-stg.yml

- template: stages/deploy.yml
  parameters:
    env: dev
    DependsOn: Build
    appName: '$(WebAppNameDev)'
    stageName: Dev

- template: stages/deploy.yml
  parameters:
    env: test
    DependsOn: Dev
    appName: '$(WebAppNameTest)'
    stageName: Test

- template: stages/deploy.yml
  parameters:
    env: staging
    DependsOn: Dev
    appName: '$(WebAppNameStaging)'
    stageName: Test