trigger:
- '*'

variables:
  buildConfiguration: 'Release'

stages:
- stage: 'Build'
  displayName: 'Build the web application'
  jobs: 
  - job: 'Build'
    displayName: 'Build job'
    pool:
      vmImage: 'ubuntu-20.04'
      demands:
      - npm

    variables:
      wwwrootDir: 'Tailspin.SpaceGame.Web/wwwroot'
      dotnetSdkVersion: '5.x'

    steps:
    - template: steps/pre-build.yml
        
    - template: steps/build.yml
      parameters:
        buildConfiguration: 'Release'

    - template: steps/publish.yml
      parameters:
        buildConfiguration: 'Release'
- template: stages/dev-deploy.yml
  parameters:
    env: dev
     
#- stage: 'Deploy'
#  displayName: 'Deploy the web application'
#  dependsOn: Build
#  jobs:
#  - deployment: Deploy
#    pool:
 #     vmImage: 'ubuntu-20.04'
  #  environment: dev
   # variables:
#    - group: Release
#    strategy:
#      runOnce:
#        deploy:
#          steps:
#          - download: current
#            artifact: drop
#          - task: AzureWebApp@1
#            displayName: 'Azure App Service Deploy: website'
#            inputs:
#              azureSubscription: 'Resource Manager - Tailspin - Space Game'
#              appName: '$(WebAppName)'
              #package: '$(Pipeline.Workspace)/drop/$(buildConfiguration)/*.zip'