trigger:
- '*'

variables:
  buildConfiguration: 'Release'

stages:
- template: stages/build-stg.yml

- template: stages/dev-deploy.yml
  parameters:
    env: dev
    DependsOn: Build
    appName: '$(WebAppNameDev)'

- template: stages/dev-deploy.yml
  parameters:
    env: test
    DependsOn: Dev
    appName: '$(WebAppNameTest)'