stages:
- stage: 'Build'
  displayName: 'Build the web application'
  jobs: 
  - job: 'Build'
    displayName: 'Build job'
    pool:
      vmImage: 'ubuntu-20.04'
      demands:
      - npm

    steps:
    - template: ../steps/pre-build.yml
        
    - template: ../steps/build.yml
      parameters:
        buildConfiguration: 'Release'

    - template: ../steps/publish.yml
      parameters:
        buildConfiguration: 'Release'