parameters:
  buildConfiguration: 'Release'
  env: ''
  DependsOn: []
  appName: ''
  stageName: ''

stages:
- stage: ${{ parameters.stageName }}
  displayName: 'Deploy to the ${{ parameters.env }} environment'
  jobs:
  - deployment: Deploy
    pool:
      vmImage: 'ubuntu-20.04'
    environment: ${{ parameters.env }}
    variables:
    - group: Release
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: drop
          - task: AzureWebApp@1
            displayName: 'Azure App Service Deploy: website'
            inputs:
              azureSubscription: 'Resource Manager - Tailspin - Space Game'
              appName: '${{ parameters.appName }}'
              package: '$(Pipeline.Workspace)/drop/${{ parameters.buildConfiguration }}/*.zip'